### ISSUE TITLE
Hello World in Golang

### ISSUE THREAD

**Issue by Shishirr17** [Karamraj/hacktoberfest2023#17]

**Comment by Karamraj** [comment]
@Shishirr17 Python Language file has already been added. Please choose another language.

**Comment by Karamraj** [comment]
@Shishirr17 Assigned. Please star the repository and make sure to follow me (https://github.com/Karamraj/). Please comment once you have starred this repository and followed me, I will give the labels.

**Comment by Shishirr17** [comment]
i have starred the repo and also followed u and posted the PR
