### ISSUE TITLE
Hello Word in Ruby

### ISSUE THREAD

**Issue by GaganChaudhary6378** [Karamraj/hacktoberfest2023#18]
Hi , I want to work on this . Can you please assign it to me @Karamraj .

**Comment by Karamraj** [comment]
@GaganChaudhary6378 We are only taking Hello Word Core in this repo.

**Comment by GaganChaudhary6378** [comment]
Is it fine now?

**Comment by Karamraj** [comment]
@GaganChaudhary6378 Assigned. Please star the repository and make sure to follow me (https://github.com/Karamraj/). Please comment once you have starred this repository and followed me, I will give the labels.

**Comment by Karamraj** [comment]
Resolved.
