### ISSUE TITLE
Hello world in Vb.net

### ISSUE THREAD

**Issue by SayaliMarathe-13** [Karamraj/hacktoberfest2023#39]

**Comment by SayaliMarathe-13** [comment]
I want to add a "Hello World" in java....I started following you and starts this repo
could you please assign this to me

**Comment by Karamraj** [comment]
@SayaliMarathe-13 Hello World in Java already exists. Please choose any other language!

**Comment by SayaliMarathe-13** [comment]
Can I choose vb.net

**Comment by Karamraj** [comment]
@SayaliMarathe-13 Yes you can.

**Comment by SayaliMarathe-13** [comment]
I done it, Please label it as Hacktoberfest-accepted and merge it

**Comment by SayaliMarathe-13** [comment]
please add a label
