### ISSUE TITLE
Hello world in C

### ISSUE THREAD

**Issue by Niranchana01** [Karamraj/hacktoberfest2023#5]
@Karamraj I'll add hello world in **C language**. Kindly assign it to me under hacktoberfest.
Thanks in advance

**Comment by Karamraj** [comment]
@Niranchana01 Assigned. Please star the repository and make sure to follow me (https://github.com/Karamraj/)

**Comment by Pratikdate** [comment]
Assigned me

**Comment by ghostbadfame** [comment]
I am interested can you please assign me this issue for hacktoberfest 2023

**Comment by Karamraj** [comment]
@ghostbadfame Already been done by someone.
