### ISSUE TITLE
Hello World in Java

### ISSUE THREAD

**Issue by kom-senapati** [Karamraj/hacktoberfest2023#8]
I added the java file.
I also added my photo to the static/images folder.
But I dont know how to add my info.

**Comment by Pratikdate** [comment]
Assigned me

**Comment by Karamraj** [comment]
> I added the java file.
> 
> I also added my photo to the static/images folder.
> 
> But I dont know how to add my info.

Assigned. Please star the repository and make sure to follow me (https://github.com/Karamraj/)

**Comment by ghostbadfame** [comment]
I am interested can you please assign me this issue for hacktoberfest 2023

**Comment by Karamraj** [comment]
@ghostbadfame Java File has been already added. You can open up a new PR or make a new Issue.
